# https://docs.docker.com/reference/dockerfile/#from
FROM mcr.microsoft.com/devcontainers/php:1-8.2-bullseye

# https://docs.docker.com/reference/dockerfile/#user
USER daemon

# https://docs.docker.com/reference/dockerfile/#healthcheck
HEALTHCHECK NONE
